// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvGW1BdNwkSGalw4hZ-Uj5Cuj5_qHB79g',
    appId: '1:711075801410:web:f5139cc7cda146512040db',
    messagingSenderId: '711075801410',
    projectId: 'efreigr2',
    authDomain: 'efreigr2.firebaseapp.com',
    storageBucket: 'efreigr2.appspot.com',
    measurementId: 'G-Q1XJWWXG5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNv16Qa7bn_7NF_g6OkSvbNUBF05OHKSQ',
    appId: '1:711075801410:android:a92df6f0e823a8b02040db',
    messagingSenderId: '711075801410',
    projectId: 'efreigr2',
    storageBucket: 'efreigr2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjbALLLT-pnkVTw6HAp3ykDb7OHBAgW_Y',
    appId: '1:711075801410:ios:2eb03d7d556c35172040db',
    messagingSenderId: '711075801410',
    projectId: 'efreigr2',
    storageBucket: 'efreigr2.appspot.com',
    iosBundleId: 'com.example.efreigrp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjbALLLT-pnkVTw6HAp3ykDb7OHBAgW_Y',
    appId: '1:711075801410:ios:01a1a9753c7c7d142040db',
    messagingSenderId: '711075801410',
    projectId: 'efreigr2',
    storageBucket: 'efreigr2.appspot.com',
    iosBundleId: 'com.example.efreigrp2.RunnerTests',
  );
}
